trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.Test.csproj'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
    publishLocation: 'Container'